name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.1
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to master
      if: success()
      run: |
        git config --global user.email "amit007.mail2@gmail.com"
        git config --global user.name "amitlvs"
        git checkout master
        git pull
        cp -r build/* ./
        git add .
        git commit -m "Auto-deploy from development branch"
        git push
